services:
  - type: web
    name: welfare-committee-form
    env: node
    buildCommand: npm install && npm run build
    startCommand: bash init-data-dir.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: /opt/render/project/src/data/welfare_committee.db
      - key: MONGODB_URI
        sync: false # This will be set manually in Render dashboard
      - key: FRONTEND_URL
        value: https://welfare-committee-form.onrender.com
      - key: VITE_API_URL
        value: https://welfare-committee-form.onrender.com
      - key: UPLOADS_DIR
        value: /opt/render/project/src/data/uploads
      - key: EXPORTS_DIR
        value: /opt/render/project/src/data/exports
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1